name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: sudo apt-get update && sudo apt-get install -y iverilog

      - name: Build and run testbench
        run: |
          iverilog -o nvme_top_tb.out nvme_top.v nvme_registers.v nvme_top_tb.v
          vvp nvme_top_tb.out
